[tool.poetry]
name = "beauty-master"
version = "0.1.0"
description = ""
authors = ["Mark Semenov <semenovmark07@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.2.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
