# Generated by Django 5.2.5 on 2025-09-12 15:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(unique=True)),
                ('end', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Выходной день',
                'verbose_name_plural': 'Выходные дни',
                'ordering': ['-start', 'end'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='daysoff_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('start', models.TimeField(blank=True, null=True)),
                ('end', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Выходной день',
                'verbose_name_plural': 'Выходные дни',
                'ordering': ['-date', 'start'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='timeoff_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('language', models.CharField(default='no', max_length=5)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No show')], default='PENDING', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-starts_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='appt_ends_after_starts'), models.UniqueConstraint(fields=('starts_at',), name='uniq_start_single_master')],
            },
        ),
    ]
