# Generated by Django 5.2.5 on 2025-08-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(unique=True)),
                ('end', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Выходной день',
                'verbose_name_plural': 'Выходные дни',
                'ordering': ['-start', 'end'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end__gt', models.F('start'))), name='daysoff_end_after_start')],
            },
        ),
    ]
