# Generated by Django 5.2.5 on 2025-09-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='daysoff',
            name='daysoff_end_after_start',
        ),
        migrations.AddConstraint(
            model_name='daysoff',
            constraint=models.CheckConstraint(condition=models.Q(('end__gte', models.F('start'))), name='daysoff_end_after_start'),
        ),
    ]
