# Generated by Django 5.2.5 on 2025-09-14 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('master_notify', 'Notify Master'), ('client_notify', 'Client Notify'), ('client_reminder', 'Client Reminder')], max_length=50)),
                ('payload', models.JSONField()),
                ('execute_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
