# Generated by Django 5.2.5 on 2025-09-18 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
