# Generated by Django 5.2.5 on 2025-09-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_outboxevent_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboxevent',
            name='booking_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['processed', 'execute_at'], name='notificatio_process_a58c9e_idx'),
        ),
        migrations.AddIndex(
            model_name='outboxevent',
            index=models.Index(fields=['booking_id'], name='notificatio_booking_741c91_idx'),
        ),
    ]
